name: 部署文档

on:
  push:
    branches:
      - 'release/v**'

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i -g yarn
      - run: yarn
      - run: yarn docs:build
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: docs-dist