name: 部署文档

on:
  push:
    branches:
      - 'release/v**'

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i -g yarn
      - run: yarn
      - run: yarn docs:build
      - run: git symbolic-ref HEAD ref/heads/gh-pages
      - run: rm -rf docs && mv docs-dist docs
      - run: git add docs
      - run: git commit -m ":wrench: 文档"
      - run: git push -u origin gh-pages
